# Generated by Django 4.2.1 on 2023-07-31 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_faceloginlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faceloginlog',
            old_name='profile',
            new_name='user',
        ),
    ]
