# Generated by Django 4.2.1 on 2023-08-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_rename_profile_faceloginlog_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pin",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="pin"
            ),
        ),
    ]
