# Generated by Django 4.2.6 on 2023-10-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user", "0011_user_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                related_name="custom_user_set", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                related_name="custom_user_set_permissions", to="auth.permission"
            ),
        ),
        migrations.DeleteModel(
            name="FaceLoginLog",
        ),
    ]
