# Generated by Django 4.2.6 on 2024-11-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True, verbose_name='User Agent')),
                ('device', models.CharField(blank=True, max_length=200, null=True, verbose_name='Device Name')),
                ('browser_version', models.CharField(blank=True, max_length=200, null=True, verbose_name='Browser version')),
                ('os', models.CharField(blank=True, max_length=200, null=True, verbose_name='OS')),
                ('os_version', models.CharField(blank=True, max_length=200, null=True, verbose_name='OS Version')),
                ('browser', models.CharField(blank=True, max_length=200, null=True, verbose_name='Browser')),
                ('hits', models.IntegerField(blank=True, null=True, verbose_name='Hits')),
                ('last_hit_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Hit At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name_plural': 'Web Device Analytic',
                'db_table': 'analytics_web_device',
            },
        ),
        migrations.CreateModel(
            name='IPAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(blank=True, max_length=200, null=True, verbose_name='Api Name')),
                ('ip_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='IP Address')),
                ('hits', models.IntegerField(blank=True, null=True, verbose_name='Hits')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='City')),
                ('region', models.CharField(blank=True, max_length=200, null=True, verbose_name='Region')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Country')),
                ('country_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Country Code')),
                ('latitude', models.CharField(blank=True, max_length=200, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=200, null=True, verbose_name='Longitude')),
                ('internet_provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='Internet Provider')),
                ('timezone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Timezone')),
                ('location_accuracy', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location Accuracy')),
                ('last_hit_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Hit At')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name_plural': 'IP Analytic',
                'db_table': 'analytics_ip',
            },
        ),
    ]
